[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://himanshu-portfolio.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["public/_next/static/chunks/*", "public/_next/static/media/*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[forms]]
  name = "contact"
  notifications = [
    { email = "himanshu.automator@gmail.com" }
  ] 