[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://himanshu-portfolio.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[forms]]
  name = "contact"
  notifications = [
    { email = "himanshu.automator@gmail.com" }
  ] 